version: "3.8"
services:
  slack-db-postger:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - week0
  slack_db_mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - week0
networks:
  week0:
volumes:
  mongodb_data: